name: reach
favicon: null
layout_spectrum: 0.07921716594137251
typography_spectrum: 0.5153128805104643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.18240518076345325
  lightness: 0.20401465892791748
  saturation: 0.9257667837664485
  rhythmicContrast: 0.5788326365873218
purpose: []
